### ISSUE TITLE
failed to build with android studio 1.3.2

### ISSUE THREAD

**Issue by itpp16** [sreichholf/dreamDroid#71]
Any hints or instructions how to build the apk with 1.3.2 ? errors are too many and vary between build types 19-23

**Comment by sreichholf** [comment]
Mmh, it builds totally fine here. I'm on 1.4beta but that shouldn't make any difference.

**Comment by itpp16** [comment]
I'll collect some error messages, I've tried many options from plain to setting build libraries, each with a different error, and once I solve an error another one pops up...

**Comment by itpp16** [comment]
I got it working now :)

First 2 issues:
http://stackoverflow.com/questions/32092511/resource-error-in-android-studio-after-update-no-resource-found
http://stackoverflow.com/questions/31653002/how-to-use-the-legacy-apache-http-client-on-android-m

Then this one "setLatestEventInfo":
https://github.com/OneBusAway/onebusaway-android/issues/290
https://github.com/bitstadium/HockeySDK-Android/pull/81/files

I've just disabled it for now:
MemorizingTrustManager.java:
/* Error:(385, 4) error: cannot find symbol method setLatestEventInfo(Context,String,String,PendingIntent) */
/* n.setLatestEventInfo(master.getApplicationContext(),
	master.getString(R.string.mtm_notification),
	certName, call); */

**Comment by sreichholf** [comment]
If ou want API23 please use the M branch

**Comment by itpp16** [comment]
Ah ok, tnx, all I wanted was the channel sub-menu changed, removed 'zap' because I only use stream and moved stream to the top which saves 4 remote control steps (its now 2x Ok to watch). I did send an email about it as a feature request but decided to give it a go myself.

**Comment by sreichholf** [comment]
I've read it, i just forgot to answer ;). I Do plan to add some more customizing in terms of "default short tap action".

**Comment by sreichholf** [comment]
Closing: obsolete on the 2.0 rewrite (main).
